version: '3.5'
services:

  kbengine-server:
    build:
      context: ${PWD}
      dockerfile: ${PWD}/Dockerfile
    image: kbengine:latest
    command: /bin/bash -c "sleep 20 && ./start_server.sh && sleep 5 && tail -qF logs/*.log"
    environment:
      KBE_RES_PATH: /kbengine/kbe/res/:/kbengine/server_assets/:/kbengine/server_assets/scripts/:/kbengine/server_assets/res/
      KBE_BIN_PATH: /kbengine/kbe/bin/server/
    depends_on:
      - kbengine-mysql
    networks:
      - kbengine
    ports:
      - 20013:20013 # loginapp
      - 20005:20005/udp # baseapp UDP
      - 20015:20015 # baseapp TCP
    # volumes:
    #   - ./server_assets:/kbengine/server_assets/

  kbengine-mysql:
    image: mysql:8.0.0
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: kbe
      MYSQL_PASSWORD: pwd123456
      MYSQL_DATABASE: kbe
    networks:
      - kbengine

networks:
  kbengine:
